### ISSUE TITLE
動画上で絵文字などを表示できないか。

### ISSUE THREAD

**Issue by srkppa** [yoshidan/EasyVTuberRel#1]
絵文字や短文などを画面上に表示できれば、zoom等表示する際にスタンプとして使えるのではと思いました。

**Comment by yoshidan** [comment]
2Dの絵文字表示するのもあれなので、3Dメッシュにアニメーションつけたリアクションいれたいんですけどメッシュ作ってる時間が。。。無料のasset知ってたら教えてください。
