### ISSUE TITLE
カメラについて

### ISSUE THREAD

**Issue by Rohhanabuteku** [yoshidan/EasyVTuberRel#6]
私だけかもしれないんですけども、OBSのバーチャルカメラプラグインをインストールしているとOBSを起動していなくてもOBSを勝手にカメラと認識してしまって動かないんですが、カメラの設定を変えることができるようにっていうのは可能ですかね？

**Comment by yoshidan** [comment]
現状、WebCamTexture.devicesでCamTwistを除いた、先頭のカメラを利用するようになっているので、他の仮想カメラが入っていると動かないかもしれないです。

時間見つけてカメラ選べるように対応します。

**Comment by yoshidan** [comment]
FaceTime以外のカメラからは読み取らないようにしました。こちらで動きますかね？
https://drive.google.com/file/d/1StxcHZXUV6njhgp_eRDH1AP9BBgWnoN5/view?usp=sharing

**Comment by Rohhanabuteku** [comment]
動きました！
これで多分大丈夫だと思います。ありがとうございます。
