### ISSUE TITLE
起動できません

### ISSUE THREAD

**Issue by GreenPear51** [yoshidan/EasyVTuberRel#7]
現在 Mac Air の OS 10.14.6. を使っています。

起こっているエラー：
・Resolutionなどを選択し、Playボタンをクリックした後すぐにアプリケーションが突然終了します
・その後、EasyVTuberが予期しない理由で終了しました、と表示されます（下記画像参照）
![スクリーンショット](https://user-images.githubusercontent.com/47761764/83880850-cb7c6f80-a77a-11ea-9cbe-5e6ddb3d83a4.png)

問題の詳細およびシステム構成の一部を抜粋してこちらに記載します。全体は1000行程ありますが、必要でしたらおっしゃってください。

> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Can't add a nil AVCaptureInput'
> abort() called
> terminating with uncaught exception of type NSException

何度か再試行しても同じ状況、再インストールしても同じ状況が続くためIssueとしてあげさせていただきました。

メモリは合計８GBあり、起動時は他のアプリに３GBほど使っている状態です。

ちなみに１度Zoom連携まで実現しています。（CamTwistではなくOBS (https://obsproject.com/ja/download) を利用）
PCをスリープさせた後、再度試そうとしたら全く起動できなくなりました。

**Comment by yoshidan** [comment]
EasyVTuber起動前に、他のアプリケーションでMacの内臓カメラの使っているってことはないですか。

**Comment by GreenPear51** [comment]
早速ありがとうございます。
＞他のアプリケーションでMacの内臓カメラの使っているってことはないですか。
ないです。Zoomを起動した際に突然画面が消える、再起動したら内蔵カメラが動かなくなるということはありました。今は全てのアプリを停止してEasyVTuberを起動しようとしてます。

**Comment by yoshidan** [comment]
OBSインストールして試してみました。色々いじった結果カメラのPermission削除すると
当該クラッシュ発生しますね。カメラのアクセス権チェックついてますか？

<img width="616" alt="スクリーンショット 2020-06-08 20 27 24" src="https://user-images.githubusercontent.com/958174/84025425-83518d00-a9c6-11ea-812d-c9d6a3e6e29a.png">

**Comment by GreenPear51** [comment]
ご指摘通り、カメラのアクセス権がチェックされてなくてチェックするとクラッシュは発生しなくなりました！ただ、立ち上げと同時にカメラが起動しません。

他のアプリケーションを開いてない状態でも、カメラが起動できないのですが原因わかりますでしょうか...？

**Comment by yoshidan** [comment]
OBSのVirtual Cameraの方が優先度高くなっていて、FaceTimeではなくOBS Virtual Cameraが読み取られている人がいたので、その可能性があるかもしれないです。
↓は FaceTime以外のカメラを読み取らないように修正したやつですが、これだとどうですかね？
https://drive.google.com/file/d/1StxcHZXUV6njhgp_eRDH1AP9BBgWnoN5/view?usp=sharing

**Comment by GreenPear51** [comment]
動きました！ありがとうございます！
